# Generated by Django 4.0.5 on 2022-06-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='complete'),
        ),
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='action',
            name='discription',
            field=models.TextField(blank=True, verbose_name='Discription'),
        ),
        migrations.AlterField(
            model_name='action',
            name='person',
            field=models.CharField(max_length=50, verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
    ]
