# Generated by Django 4.0.5 on 2022-06-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_action_complete_alter_action_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Important'),
        ),
        migrations.AddField(
            model_name='action',
            name='repeat',
            field=models.BooleanField(default=False, verbose_name='Repeat'),
        ),
        migrations.AddField(
            model_name='action',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='action',
            name='topic',
            field=models.CharField(default='da', max_length=50, verbose_name='Topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='complete',
            field=models.BooleanField(default=False, verbose_name='Complete'),
        ),
        migrations.AlterField(
            model_name='action',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
    ]
