# Generated by Django 4.0.5 on 2022-06-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_action_important_action_repeat_action_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('topic', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Topic')),
            ],
        ),
        migrations.AlterField(
            model_name='action',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topics'),
        ),
    ]
