# Generated by Django 4.0.5 on 2022-06-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_actions_delete_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actions',
            name='topic',
        ),
    ]
