# Generated by Django 4.0.5 on 2022-06-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_action_delete_actions_rename_topics_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='important',
        ),
    ]
