# Generated by Django 4.0.5 on 2022-06-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_action_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='repeat',
        ),
        migrations.AddField(
            model_name='action',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Important'),
        ),
    ]
