# Generated by Django 4.1.4 on 2022-12-19 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_action_repeat_action_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='complete',
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=50, verbose_name='Person')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('discription', models.TextField(blank=True, verbose_name='Discription')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Time')),
                ('important', models.BooleanField(default=False, verbose_name='Important')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.topic')),
            ],
        ),
    ]
