# Generated by Django 4.1.4 on 2022-12-19 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_alter_archive_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='person',
            field=models.ForeignKey(db_column='user_name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
