# Generated by Django 4.1.4 on 2022-12-19 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_action_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='important',
        ),
    ]
