# Generated by Django 4.1.4 on 2022-12-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_archive_important'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='date',
            field=models.DateField(auto_now=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='time',
            field=models.TimeField(auto_now=True, verbose_name='Time'),
        ),
    ]
