# Generated by Django 4.1.4 on 2023-01-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
