# Generated by Django 4.1.4 on 2023-02-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_action_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('action', models.CharField(max_length=50, verbose_name='Name of action')),
                ('kwargs', models.TextField(verbose_name='Json kwargs')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.action')),
            ],
        ),
    ]
