# Generated by Django 4.1.4 on 2023-02-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_pertask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertask',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pertask',
            name='time',
            field=models.TimeField(),
        ),
    ]
