# Generated by Django 4.1.4 on 2023-02-22 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_pertask_task_pertask_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pertask',
            name='kwargs',
            field=models.TextField(blank=True, null=True, verbose_name='Json kwargs'),
        ),
    ]
