# Generated by Django 4.1.4 on 2023-02-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_pertask_date_alter_pertask_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pertask',
            name='periodic',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
