# Generated by Django 4.1.4 on 2023-03-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_pertask_periodic'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='periodic',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
