# Generated by Django 4.1.4 on 2023-03-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_action_periodic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='periodic',
            new_name='period',
        ),
        migrations.RenameField(
            model_name='pertask',
            old_name='periodic',
            new_name='period',
        ),
        migrations.AlterField(
            model_name='action',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Title'),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('title', 'date')},
        ),
    ]
